In [66]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [67]:
import pandas as pd
import glob

path = '/content/drive/MyDrive/Dataset Arkavidia/ISPU/'

files = glob.glob(path + "indeks-standar-*.csv")
simpan = []

for i in files:
  data = pd.read_csv(i)
  mapping = {
      'pm_10': 'pm10',
      'pm_duakomalima': 'pm25',
      'lokasi_spku': 'stasiun',
      'categori': 'category'
  }

  data.rename(columns=mapping, inplace=True)

  kolom_target = ['periode_data', 'tanggal', 'stasiun', 'pm10', 'pm25',
                  'so2', 'co', 'o3', 'no2', 'max', 'critical', 'category']


  simpan_kolom = [c for c in kolom_target if c in data.columns]
  data = data[simpan_kolom]

  simpan.append(data)


data_ispu_10_22 = pd.concat(simpan, axis=0, ignore_index=True)
data_ispu_10_22['tanggal'] = pd.to_datetime(data_ispu_10_22['tanggal'], errors='coerce')
data_ispu_10_22 = data_ispu_10_22.sort_values(by='tanggal').reset_index(drop=True)


print(f'Selesai GnG',{len(files)})
print(f"Rentang data: {data_ispu_10_22['tanggal'].min()} sampai {data_ispu_10_22['tanggal'].max()}")

Selesai GnG {13}
Rentang data: 2010-01-01 00:00:00 sampai 2022-12-30 00:00:00

/tmp/ipykernel_224/2427072830.py:31: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data_ispu_10_22['tanggal'] = pd.to_datetime(data_ispu_10_22['tanggal'], errors='coerce')

**EDA Dataset 2010 - 2022**

In [68]:
data_ispu_10_22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12032 entries, 0 to 12031
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  12032 non-null  int64
 1   tanggal       12031 non-null  datetime64[ns]
 2   stasiun       12032 non-null  object
 3   pm10          12032 non-null  object
 4   pm25          2128 non-null   object
 5   so2           12032 non-null  object
 6   co            12032 non-null  object
 7   o3            12032 non-null  object
 8   no2           12032 non-null  object
 9   max           12032 non-null  object
 10  critical      10616 non-null  object
 11  category      12031 non-null  object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 1.1+ MB

In [69]:
data_ispu_10_22.head()

,periode_data,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,category
0,201001,2010-01-01,DKI2 (Kelapa Gading),---,NaN,---,---,---,---,0,NaN,TIDAK ADA DATA
1,201001,2010-01-01,DKI1 (Bunderan HI),60,NaN,4,73,27,14,73,CO,SEDANG
2,201001,2010-01-01,DKI3 (Jagakarsa),---,NaN,---,---,---,---,0,NaN,TIDAK ADA DATA
3,201001,2010-01-01,DKI4 (Lubang Buaya),---,NaN,---,---,---,---,0,NaN,TIDAK ADA DATA
4,201001,2010-01-01,DKI5 (Kebon Jeruk),---,NaN,---,---,---,---,0,NaN,TIDAK ADA DATA

In [70]:
data_ispu_10_22.tail()

,periode_data,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,category
12027,202212,2022-12-27,DKI2,36,47,58,42,20,18,58,SO2,SEDANG
12028,202212,2022-12-28,DKI3,46,66,57,41,15,19,66,"PM2,5",SEDANG
12029,202212,2022-12-29,DKI2,23,50,57,12,16,15,57,SO2,SEDANG
12030,202212,2022-12-30,DKI4,40,64,57,21,17,24,64,"PM2,5",SEDANG
12031,202212,NaT,DKI4,54,73,56,24,23,24,73,"PM2,5",SEDANG

In [71]:
data.columns

Index(['periode_data', 'tanggal', 'stasiun', 'pm10', 'so2', 'co', 'o3', 'no2',
       'max', 'critical', 'category'],
      dtype='object')

In [72]:
data_ispu_10_22.isnull().sum()

periode_data       0
tanggal            1
stasiun            0
pm10               0
pm25            9904
so2                0
co                 0
o3                 0
no2                0
max                0
critical        1416
category           1
dtype: int64

**Data Cleaning Dataset ISPU 2010-2022**

In [73]:
polutan = ['pm10', 'so2', 'co', 'o3', 'no2']

for i in polutan:
  if i in data_ispu_10_22.columns:
    data_ispu_10_22[i] = pd.to_numeric(data_ispu_10_22[i],errors='coerce')



data_ispu_10_22.isnull().sum()

periode_data       0
tanggal            1
stasiun            0
pm10            1759
pm25            9904
so2             1680
co              1579
o3              1731
no2             1638
max                0
critical        1416
category           1
dtype: int64

In [74]:
data_ispu_10_22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12032 entries, 0 to 12031
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  12032 non-null  int64
 1   tanggal       12031 non-null  datetime64[ns]
 2   stasiun       12032 non-null  object
 3   pm10          10273 non-null  float64
 4   pm25          2128 non-null   object
 5   so2           10352 non-null  float64
 6   co            10453 non-null  float64
 7   o3            10301 non-null  float64
 8   no2           10394 non-null  float64
 9   max           12032 non-null  object
 10  critical      10616 non-null  object
 11  category      12031 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(1), object(5)
memory usage: 1.1+ MB

In [75]:
data_ispu_10_22.duplicated().sum()

np.int64(0)

In [76]:
data_ispu_10_22.head()

,periode_data,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,category
0,201001,2010-01-01,DKI2 (Kelapa Gading),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,TIDAK ADA DATA
1,201001,2010-01-01,DKI1 (Bunderan HI),60.0,NaN,4.0,73.0,27.0,14.0,73,CO,SEDANG
2,201001,2010-01-01,DKI3 (Jagakarsa),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,TIDAK ADA DATA
3,201001,2010-01-01,DKI4 (Lubang Buaya),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,TIDAK ADA DATA
4,201001,2010-01-01,DKI5 (Kebon Jeruk),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,TIDAK ADA DATA

**To Do**

1. Handle Missing Values (pm10, pm25, so2, co, o3, no2,max)
2. Drop Non Information Columns ('periode_data')
3. Handle Anomaly in Max Columns
4. Handle Missing Values in critical, but before handle ,shoul encode first cz object dtype
5. Encode Object Columns (category and stasiun)

1. Drop Non Information Columns

In [77]:
data_ispu_10_22 = data_ispu_10_22.drop(columns='periode_data',
                                       axis=1)

2. Handle Anomaly in Max Columns

In [79]:
data_ispu_10_22['max'].value_counts()

max
0       1373
63       128
70       124
65       124
55       119
        ...
156        1
174        1
PM25       1
179        1
181        1
Name: count, Length: 407, dtype: int64

In [89]:
import numpy as np

data_ispu_10_22['max'] = data_ispu_10_22['max'].astype(str).str.strip()

data_ispu_10_22['max'] = pd.to_numeric(data_ispu_10_22['max'],errors='coerce')

data_ispu_10_22['max'] = data_ispu_10_22['max'].astype('Int64')

data_ispu_10_22['max'] = data_ispu_10_22['max'].replace(0, np.nan)

dtype = data_ispu_10_22['max'].dtypes
cekMV = data_ispu_10_22['max'].isnull().sum()

print('Data Type Max Column Now:',dtype)
print('Missing Values in Max Columns:',cekMV)

Data Type Max Column Now: Int64
Missing Values in Max Columns: 1420

In [90]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   periode_data  365 non-null    int64
 1   tanggal       365 non-null    object
 2   stasiun       365 non-null    object
 3   pm10          365 non-null    int64
 4   so2           365 non-null    int64
 5   co            365 non-null    int64
 6   o3            365 non-null    int64
 7   no2           365 non-null    int64
 8   max           365 non-null    int64
 9   critical      365 non-null    object
 10  category      365 non-null    object
dtypes: int64(7), object(4)
memory usage: 31.5+ KB

In [92]:
data_ispu_10_22.isnull().sum()

tanggal        1
stasiun        0
pm10        1759
pm25        9904
so2         1680
co          1579
o3          1731
no2         1638
max         1420
critical    1416
category       1
dtype: int64

PM25 baru ada ketika 2021 dan 2022

In [ ]:
#untuk kolom pm25 bisa diisi dengan median / menggunakan pm 10
#encode categorical variables

kayak nya abis ini data 2023 langsung gabung aja deh jan dipisah pisah